environment:
  RUST_BACKTRACE: 1

  matrix:
  - TARGET: x86_64-pc-windows-gnu

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain nightly
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V
  - cargo install -f ptx-linker
  - rustup target add nvptx64-nvidia-cuda

build: "off"

test_script:
  - cargo test --verbose

branches:
  only:
    - master
